/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leanMind.katas;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class StringCalculatorTest extends StringCalculator{

	@Test
	public void testCalculateStringLetters() {
		String preCond= "a";
		int res = calculateString(preCond);
		assertTrue(res == 0);
	}
	
	@Test
	public void testCalculateStringSingleNumber() {
		String preCond= "1";
		int res = calculateString(preCond);
		assertTrue(res == 1);
	}
	
	@Test
	public void testCalculateStringBlankAndNumber() {
		String preCond= " 1";
		int res = calculateString(preCond);
		assertTrue(res == 1);
	}
	
	@Test
	public void testCalculateStringEmpty() {
		String preCond= "";
		int res = calculateString(preCond);
		assertTrue(res == 0);
	}
	
	@Test
	public void testSingleGroupValueLetter() {
		String preCond= "a";
		int res = singleGroupValue(preCond);
		assertTrue(res == 0);
	}
	
	@Test
	public void testSingleGroupValueNumber() {
		String preCond= "1";
		int res = singleGroupValue(preCond);
		assertTrue(res == 1);
	}
	
}
