/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leanMind.katas;

import static org.junit.Assert.assertTrue;

import org.junit.Ignore;
import org.junit.Test;

public class StringCalculatorTest extends StringCalculator{

	@Test
	public void testCalculateStringLetters() {
		String preCond= "a";
		int res = calculateString(preCond);
		assertTrue(res == 0);
	}
	
	@Test
	public void testCalculateStringSingleNumber() {
		String preCond= "1";
		int res = calculateString(preCond);
		assertTrue(res == 1);
	}
	
	@Test
	public void testCalculateStringBlankAndNumber() {
		String preCond= " 1";
		int res = calculateString(preCond);
		assertTrue(res == 1);
	}
	
	@Test
	public void testCalculateStringEmpty() {
		String preCond= "";
		int res = calculateString(preCond);
		assertTrue(res == 0);
	}
	
	@Test
	public void testCalculateSeveralNumbersString() {
		String preCond= "1, 1";
		int res = calculateString(preCond);
		assertTrue(res == 2);
	}
	
	@Test
	public void testCalculateNumbersAndLettersString() {
		String preCond= "1, a";
		int res = calculateString(preCond);
		assertTrue(res == 1);
	}
	
	@Test
	public void testCalculateManyNumbersString() {
		String preCond= "1, 1, 3";
		int res = calculateString(preCond);
		assertTrue(res == 5);
	}
	
	@Test
	public void testCalculateStringWithSeparatorEmbeeded() {
		String preCond= "//#;1#2#3";
		int res = calculateString(preCond);
		assertTrue(res == 6);
	}
	
	@Test
	public void testFetchSeparatorNoSeparator() {
		String preCond= "1111";
		String res = fetchSeparator(preCond);
		assertTrue(res.equals(","));
	}
	
	@Test
	public void testFetchSeparator() {
		String preCond= "//#;";
		String res = fetchSeparator(preCond);
		assertTrue(res.equals("#"));
	}
	
	@Test
	public void testSingleGroupValueLetter() {
		String preCond= "a";
		int res = singleGroupValue(preCond);
		assertTrue(res == 0);
	}
	
	@Test
	public void testSingleGroupValueNumber() {
		String preCond= "1";
		int res = singleGroupValue(preCond);
		assertTrue(res == 1);
	}
	
}
