/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leanMind.katas;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class StringCalculatorTest extends StringCalculator{

	@Test
	public void testCalculateStringLetters() {
		String preCond= "a";
		int res = calculateString(preCond);
		assertTrue(res == 0);
	}
	
}
